<#
.SYNOPSIS
Adds some needed packages to a Vite
#>
function Add-MyPackagesToVite {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [switch]$UseDaisyUi
    )
    process {
        [hashtable]$missingCompilerOptions = [ordered]@{
            <# Vite Default Settings #>
            'useDefineForClassFields'    = $true
            'allowImportingTsExtensions' = $true
        }

        # Install npm packages according to package.json generated by Vite
        npm i
        <# Git #>
        Initialize-MyGit
        git add .
        git commit -m 'Add all the files generated by Vite'
        <# npm-check-updates #>
        Install-MyNpmCheckUpdates
        <# TypeScript #>
        # Make tsconfig more strict
        git rm '.\tsconfig.json'
        Install-MyTypeScript -UseReact -NoEmit
        [hashtable]$tsConfig = Import-MyJSON -LiteralPath '.\tsconfig.json' -AsHashTable
        # Add Vite default settings
        $missingCompilerOptions.GetEnumerator() | ForEach-Object {
            $tsConfig.compilerOptions.Add($_.Key, $_.Value)
        }
        $tsConfig.compilerOptions.target = 'es2020'
        $tsConfig.compilerOptions.module = 'esnext'
        $tsConfig.compilerOptions.moduleResolution = 'bundler'
        Export-MyJSON -LiteralPath '.\tsconfig.json' -CustomObject $tsConfig
        git add './tsconfig.json'
        git commit -m 'Make tsconfig more strict'
        <# ESLint #>
        # Make eslintrc more strict
        Install-MyESLint -UseBrower -UseTypeScript -UseReact -UseJest
        [hashtable]$eslintrc = Import-MyJSON -LiteralPath '.\.eslintrc.json' -AsHashTable
        # Add Vite default settings
        $eslintrc.env.Remove('es2021')
        $eslintrc.env.Add('es2020', $true)
        $eslintrc.plugins += 'react-refresh'
        $eslintrc.rules.Add('react-refresh/only-export-components', @(
                'warn', @{
                    allowConstantExport = $true
                }
            ))
        # Vite uses absolute path ('/') to access public directory
        $eslintrc.rules.Add('import/no-absolute-path', 'off')
        Export-MyJSON -LiteralPath '.\.eslintrc.json' -CustomObject $eslintrc
        git rm '.\.eslintrc.cjs'
        git add '.\.eslintrc.json'
        git commit -m 'Make eslintrc more strict'
        <# Jest #>
        Install-MyJest -UseBrowser -UseReact
        <# Prettier #>
        Install-MyPrettier -UseTailwindcss
        <# Tailwind CSS #>
        Install-MyTailwindCss -IsVite
        <# Rename .js .cjs for config files to work in type: module #>
        Rename-MyFileExtension -OldExtension 'js' -NewExtension 'cjs' -UseGitMv
        git commit -m 'Rename .js .cjs for config files to work in `type: module`'
    }
}

Export-ModuleMember -Function Add-MyPackagesToVite
